### ISSUE TITLE
TypeError when configuring new scene

### ISSUE THREAD

**Issue by Unarekin** [Unarekin/FoundryVTT-Battle-Transitions#13]
Updating the configuration of a new scene in 1.1.0-alpha2 throws the following TypeError:
```
TypeError: Cannot read properties of undefined (reading 'version')
    at qt.Version (module.js:195:32622)
    at qt.NeedsMigration (module.js:195:32419)
    at t.GetSceneConfiguration (module.js:195:39064)
    at Scene.prototype.update#battle-transitions (module.js:200:754)
    at call_wrapper [as call_wrapper] (libWrapper-wrapper.js:639:16)
    at Scene.prototype.update#0 (libWrapper-wrapper.js:193:20)
    at SceneConfig._updateObject (foundry.js:80732:18)
    at async SceneConfig._onSubmit (foundry.js:6665:7)
```

**Comment by Unarekin** [comment]
Fixed in 1.1.0-alpha3
